### PR TITLE
12 homepage dev

### PR DESCRIPTION
**Pull request by piper-jones**

### CODE REVIEW

**Review by rileycleavenger — CHANGES_REQUESTED** [review]
This looks so good!!! Nice work guys!! 

I think for the filters there should be an option for spending range that should be either a slider with two points where you adjust a range or two textboxes. Add that and then I can approve.

**Comment by rileycleavenger** [comment]
> This looks so good!!! Nice work guys!!
> 
> I think for the filters there should be an option for spending range that should be either a slider with two points where you adjust a range or two textboxes. Add that and then I can approve.

@piper-jones @madwirblet not sure if you guys saw

**Comment by madwirblet** [comment]
Changes made

**Review by rileycleavenger — APPROVED** [review]
LGTM! Slider bar looks good!

**Pull request merged**
