### PR TITLE
Set up the Nav bar and Router

### LINKED ISSUE #3: Setup Navbar/Router
- StockBuddy (Home) page
- Login page
- Signup page
- User page
- About page
- [ ] Style the Navbar
- [ ] Setup a Navbar with the following page options:
- [ ] Setup the React router

### PR DESCRIPTION
**Pull request by piper-jones**
This pull request implements the router functionality and a functional navigation bar.

Resolves #3

### CODE REVIEW

**Review by rileycleavenger — CHANGES_REQUESTED** [review]
It's failing to deploy on Vercel due to build errors:
image

When I try to run `npm start` I get these build errors so I think it might have to do with that:
image

**See if you can fix it and I can rereview, lmk if you need help.**

**Review by rileycleavenger — APPROVED** [review]
LGTM! Once @dos-2 approves you're good to merge into main

**Comment by dos-2** [comment]
what are we doing about the merge conflicts? @rileycleavenger

**Comment by rileycleavenger** [comment]
@dos-2 Do you want to go through how you solve merge conflicts on the call today?

**Comment by dos-2** [comment]
Great job Piper!

**Review by dos-2 — APPROVED** [review]
Great job Piper!

**Pull request merged**
