### PR TITLE
Added Components and Message in each File

### PR DESCRIPTION
**Pull request by Dravani**
For Issue, Make Page Components #4.

### CODE REVIEW

**Review by rileycleavenger — CHANGES_REQUESTED** [review]
I think this is my fault for not clarifying this, but the project is setup to use typescript (.tsx) files, so if you can change these to typescript that would be awesome. my bad for not telling you guys that part, but otherwise the file organization looks good.

**Comment by Dravani** [comment]
Made changes

**Review by rileycleavenger — APPROVED** [review]
LGTM!

**Comment by rileycleavenger** [comment]
closes #4

**Pull request merged**
